.TH "detour Directory Reference" 3 "Fri Oct 21 2022" "Version 0.5.37.bcb1f0a69648" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detour Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdetour\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_handle\&.h\fP"
.br
.ti -1c
.RI "file \fBdetour_interface\&.h\fP"
.br
.in -1c
