.TH "metacall Directory Reference" 3 "Fri Oct 21 2022" "Version 0.5.37.bcb1f0a69648" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metacall Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmetacall\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_allocator\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_error\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_fork\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_log\&.h\fP"
.br
.ti -1c
.RI "file \fBmetacall_value\&.h\fP"
.br
.in -1c
