.TH "dynlink_type.h" 3 "Fri Oct 21 2022" "Version 0.5.37.bcb1f0a69648" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynlink_type.h
.SH SYNOPSIS
.br
.PP
\fC#include <dynlink/dynlink_api\&.h>\fP
.br
\fC#include <portability/portability_library_path\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct dynlink_type * \fBdynlink\fP"
.br
.ti -1c
.RI "typedef portability_library_path_str \fBdynlink_library_path_str\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const typedef char * \fBdynlink_path\fP"
.br
.ti -1c
.RI "const typedef char * \fBdynlink_name\fP"
.br
.ti -1c
.RI "const typedef char * \fBdynlink_symbol_name\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct dynlink_type* \fBdynlink\fP"
Dynamically linked shared object handle 
.SS "typedef portability_library_path_str \fBdynlink_library_path_str\fP"
Dynamically linked shared object symbol name 
.SH "Variable Documentation"
.PP 
.SS "const typedef char* dynlink_path"
Dynamically linked shared object path 
.SS "const typedef char* dynlink_name"
Dynamically linked shared object name 
.SS "const typedef char* dynlink_symbol_name"
Dynamically linked shared object symbol name 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
