.TH "loader_impl_data.h" 3 "Fri Oct 21 2022" "Version 0.5.37.bcb1f0a69648" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loader_impl_data.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBloader_impl_data\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBloader_impl_data\fP"

.PP
Generic handle for implementation data of a loader\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
