.TH "log_policy_stream_stdio_ctor" 3 "Fri Oct 21 2022" "Version 0.5.37.bcb1f0a69648" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_policy_stream_stdio_ctor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/cpp\-design\-pattern/cpp\-design\-pattern/core/source/log/include/log/log_policy_stream_stdio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBstream\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "FILE* log_policy_stream_stdio_ctor::stream"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
