.TH "pair" 3 "Fri Oct 21 2022" "Version 0.5.37.bcb1f0a69648" "MetaCall" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pair
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </home/runner/work/cpp\-design\-pattern/cpp\-design\-pattern/core/source/adt/include/adt/adt_bucket\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* pair::key"

.SS "void* pair::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for MetaCall from the source code\&.
